export const termsPageStyles = {
  container: 'flex min-h-screen flex-col items-center bg-zinc-50 px-4 pt-12 dark:bg-zinc-950',
  card: 'w-full max-w-sm rounded-2xl bg-white px-8 py-10 shadow-md dark:bg-zinc-900',
  title: 'mb-8 text-center text-2xl font-bold text-zinc-900 dark:text-white',
  termList: 'flex flex-col gap-3',
  allAgreeRow: 'flex items-center gap-3 rounded-xl border border-zinc-300 bg-zinc-50 px-4 py-3 dark:border-zinc-600 dark:bg-zinc-800',
  allAgreeLabel: 'text-sm font-semibold text-zinc-800 dark:text-zinc-200 cursor-pointer select-none',
  divider: 'my-1 border-t border-zinc-100 dark:border-zinc-700',
  termItem: 'flex items-center justify-between rounded-xl border border-zinc-200 px-4 py-3 dark:border-zinc-700',
  termLeft: 'flex items-center gap-3',
  termTitle: 'text-sm font-medium text-zinc-800 dark:text-zinc-200',
  termRight: 'flex items-center gap-3',
  checkbox: 'h-4 w-4 cursor-pointer accent-zinc-800 dark:accent-zinc-200',
  requiredBadge: 'rounded-full bg-red-100 px-2 py-0.5 text-xs font-semibold text-red-600 dark:bg-red-900 dark:text-red-300',
  optionalBadge: 'rounded-full bg-zinc-100 px-2 py-0.5 text-xs font-semibold text-zinc-500 dark:bg-zinc-700 dark:text-zinc-400',
  detailLink: 'text-xs text-zinc-400 underline underline-offset-2 hover:text-zinc-600 dark:text-zinc-500 dark:hover:text-zinc-300',
  submitButton: 'mt-6 w-full rounded-xl bg-zinc-900 py-3 text-sm font-semibold text-white hover:bg-zinc-700 transition-colors dark:bg-white dark:text-zinc-900 dark:hover:bg-zinc-200',
  submitButtonDisabled: 'mt-6 w-full rounded-xl bg-zinc-200 py-3 text-sm font-semibold text-zinc-400 cursor-not-allowed dark:bg-zinc-700 dark:text-zinc-500',
};
