export const termsPageStyles = {
  page: 'flex min-h-[calc(100vh-3.5rem)] flex-col items-center justify-center bg-[#f8f9fc] px-4 dark:bg-[#07070f]',
  header: 'mb-8 flex flex-col items-center gap-3',
  logoMark: 'flex h-12 w-12 items-center justify-center rounded-2xl bg-indigo-600 text-sm font-bold text-white shadow-lg shadow-indigo-500/30',
  title: 'text-xl font-bold tracking-tight text-zinc-900 dark:text-zinc-50',
  subtitle: 'text-sm text-zinc-500 dark:text-zinc-400',
  card: 'w-full max-w-sm rounded-2xl border border-zinc-200/80 bg-white p-6 shadow-sm dark:border-white/5 dark:bg-[#0f0f1a]',
  termList: 'flex flex-col gap-1.5',
  allAgreeRow: 'flex items-center gap-3 rounded-xl border border-indigo-100 bg-indigo-50/60 px-4 py-3 dark:border-indigo-500/10 dark:bg-indigo-500/5',
  allAgreeLabel: 'cursor-pointer select-none text-sm font-semibold text-indigo-700 dark:text-indigo-400',
  divider: 'my-2 border-t border-zinc-100 dark:border-white/5',
  termItem: 'flex items-center justify-between rounded-lg px-3 py-2.5',
  termLeft: 'flex items-center gap-3',
  termTitle: 'text-sm text-zinc-700 dark:text-zinc-300',
  termRight: 'flex items-center gap-2.5',
  checkbox: 'h-4 w-4 cursor-pointer rounded accent-indigo-600',
  requiredBadge: 'rounded-md bg-rose-50 px-1.5 py-0.5 text-[10px] font-semibold text-rose-600 dark:bg-rose-500/10 dark:text-rose-400',
  optionalBadge: 'rounded-md bg-zinc-100 px-1.5 py-0.5 text-[10px] font-medium text-zinc-500 dark:bg-white/5 dark:text-zinc-500',
  detailLink: 'text-xs text-indigo-400 underline underline-offset-2 hover:text-indigo-600 dark:text-indigo-500 dark:hover:text-indigo-300',
  submitButton: 'mt-4 h-11 w-full rounded-xl bg-indigo-600 text-sm font-semibold text-white shadow-sm shadow-indigo-500/20 transition-colors hover:bg-indigo-700',
  submitButtonDisabled: 'mt-4 h-11 w-full cursor-not-allowed rounded-xl bg-zinc-100 text-sm font-semibold text-zinc-400 dark:bg-white/5 dark:text-zinc-600',
};
